import type { ConfigRules, PriceItem, StoreProfile } from "@/lib/types";

export const DEFAULT_PRICE_LIST: PriceItem[] = [
  {
    item_id: "lash_001",
    category: "EYELASH EXTENSION",
    item_name: "輕盈上眼睫毛",
    original_price: "668 / 998",
    share_price: "598",
    active: true,
    notes: "",
  },
  {
    item_id: "lash_002",
    category: "EYELASH EXTENSION",
    item_name: "設計全眼綜合",
    original_price: "866 / 1298",
    share_price: "778",
    active: true,
    notes: "",
  },
  {
    item_id: "lash_003",
    category: "EYELASH EXTENSION",
    item_name: "歐美設計",
    original_price: "1456 / 1596",
    share_price: "1289",
    active: true,
    notes: "",
  },
  {
    item_id: "vip_001",
    category: "MISS EYE DOR VIP高級訂製系列",
    item_name: "日式睫毛",
    original_price: "1568 / 1960",
    share_price: "1398",
    active: true,
    notes: "",
  },
  {
    item_id: "vip_002",
    category: "MISS EYE DOR VIP高級訂製系列",
    item_name: "日式歐美睫毛",
    original_price: "2288 / 2560",
    share_price: "000",
    active: true,
    notes: "分享價無效，回退原價",
  },
  {
    item_id: "treatment_eye_001",
    category: "TREATMENT（眼部治療）",
    item_name: "眼部深層清潔",
    original_price: "168 / 68",
    share_price: "148",
    active: true,
    notes: "去蟎蟲、堵塞毛孔、過多油脂分泌等",
  },
  {
    item_id: "embroidery_001",
    category: "紋繡",
    item_name: "霧感眉",
    original_price: "2680 / 3680",
    share_price: "-",
    active: true,
    notes: "輕輕掃過的視覺感，幼態輕盈又方便",
  },
  {
    item_id: "embroidery_002",
    category: "紋繡",
    item_name: "野生線條眉",
    original_price: "6680 / 12800",
    share_price: "-",
    active: true,
    notes: "呈現原來生長的效果，讓眉毛立體讓五官更立體",
  },
  {
    item_id: "embroidery_003",
    category: "紋繡",
    item_name: "補/缺",
    original_price: "1380",
    share_price: "-",
    active: true,
    notes: "如果你有缺少即可補上幾根、無痕",
  },
  {
    item_id: "embroidery_004",
    category: "紋繡",
    item_name: "霧感眼線",
    original_price: "2380 / 2980",
    share_price: "-",
    active: true,
    notes: "讓睫毛增加色度，有神而無痕",
  },
  {
    item_id: "embroidery_005",
    category: "紋繡",
    item_name: "裸唇感",
    original_price: "3680",
    share_price: "-",
    active: true,
    notes: "調整唇色，讓唇恢復自然健康色，無妝感",
  },
  {
    item_id: "embroidery_006",
    category: "紋繡",
    item_name: "無創洗眉",
    original_price: "1980",
    share_price: "-",
    active: true,
    notes: "不破皮的清洗方式",
  },
  {
    item_id: "nail_001",
    category: "美甲",
    item_name: "手純色",
    original_price: "298 / 468up",
    share_price: "258 / 428",
    active: true,
    notes: "區間價需手動輸入",
  },
  {
    item_id: "nail_002",
    category: "美甲",
    item_name: "基礎款",
    original_price: "388up",
    share_price: "338",
    active: true,
    notes: "",
  },
  {
    item_id: "nail_003",
    category: "美甲",
    item_name: "手繪",
    original_price: "688up",
    share_price: "598",
    active: true,
    notes: "",
  },
  {
    item_id: "nail_004",
    category: "美甲",
    item_name: "延長",
    original_price: "150up",
    share_price: "120",
    active: true,
    notes: "",
  },
  {
    item_id: "nail_005",
    category: "美甲",
    item_name: "腳部護理",
    original_price: "468up",
    share_price: "418",
    active: true,
    notes: "",
  },
  {
    item_id: "hair_001",
    category: "髮型基礎服務",
    item_name: "髮型師剪發 Hair cut",
    original_price: "600up",
    share_price: "367up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_002",
    category: "髮型基礎服務",
    item_name: "髮型師洗吹",
    original_price: "150up",
    share_price: "98up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_003",
    category: "髮型基礎服務",
    item_name: "Washing blow dry",
    original_price: "-",
    share_price: "-",
    active: true,
    notes: "三次送一次",
  },
  {
    item_id: "color_001",
    category: "染髮系列 COLOR",
    item_name: "INNOA無氨染 No ammonia",
    original_price: "980up",
    share_price: "780up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "color_002",
    category: "染髮系列 COLOR",
    item_name: "歐萃雅 L'oreal",
    original_price: "880up",
    share_price: "680up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "color_003",
    category: "染髮系列 COLOR",
    item_name: "挑染 highlights",
    original_price: "1000up",
    share_price: "780up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "color_004",
    category: "染髮系列 COLOR",
    item_name: "水霧染 (toner)",
    original_price: "580up",
    share_price: "280up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_treatment_001",
    category: "護理系列 Treatment",
    item_name: "歐萃雅深層滋養發膜",
    original_price: "580up",
    share_price: "280up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_treatment_002",
    category: "護理系列 Treatment",
    item_name: "L'oreal",
    original_price: "-",
    share_price: "-",
    active: true,
    notes: "三次送一次",
  },
  {
    item_id: "hair_treatment_003",
    category: "護理系列 Treatment",
    item_name: "吸金護理 metal-DX",
    original_price: "680up",
    share_price: "460up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_treatment_004",
    category: "護理系列 Treatment",
    item_name: "卡詩角子醬護理 Kerastase Chronological Treatment",
    original_price: "1500up",
    share_price: "880up",
    active: true,
    notes: "up 價需手動輸入",
  },
  {
    item_id: "hair_treatment_005",
    category: "護理系列 Treatment",
    item_name: "歐萃雅頭皮清潔發膜 Scalp Treatment",
    original_price: "580up",
    share_price: "280up",
    active: true,
    notes: "up 價需手動輸入",
  },
];

export const DEFAULT_STORE_PROFILE: StoreProfile = {
  store_name_zh: "示例美業店",
  store_name_en: "Sample Beauty Salon",
  address_zh: "請在系統設定填寫店舖地址",
  address_en: "Please set the shop address in settings",
  parking_zh: "請在系統設定填寫最近停車位",
  parking_en: "Please set nearby parking in settings",
  mtr_zh: "請在系統設定填寫最近地鐵資訊",
  mtr_en: "Please set nearby MTR info in settings",
  phone: "請在系統設定填寫電話",
  blessing_zh: "多謝你今日幫襯，祝你靚住每一日！",
  blessing_en: "Thank you for visiting us today. Have a lovely day!",
};

export function withDefaultPriceItemTranslation(item: PriceItem): PriceItem {
  return {
    ...item,
    category_en: item.category_en?.trim() || "",
    item_name_en: item.item_name_en?.trim() || "",
  };
}

for (let i = 0; i < DEFAULT_PRICE_LIST.length; i += 1) {
  DEFAULT_PRICE_LIST[i] = withDefaultPriceItemTranslation(DEFAULT_PRICE_LIST[i]);
}

export const DEFAULT_CONFIG: ConfigRules = {
  discountTiers: [
    { threshold: 10000, rate: 0.75 },
    { threshold: 5000, rate: 0.8 },
    { threshold: 3000, rate: 0.85 },
    { threshold: 1500, rate: 0.9 },
  ],
  topupQuickAmounts: [1500, 3000, 5000, 10000],
  currencyCode: "HKD",
  roundingMode: "ROUND",
  roundingUnit: 1,
  allowedPaymentMethods: ["BALANCE"],
};
